stages:
  - vetting
  - tests
  
before_script:
    - export GOROOT=/usr/lib/go-1.11
    - export GOPATH=~/go
    - export PATH=$PATH:$GOROOT/bin
    - export PATH=$PATH:$GOPATH/bin

lint:
  image: golang
  stage: vetting
  script:
    - golint -set_exit_status ./...
  allow_failure: true
  
fmt:
  image: golang
  stage: vetting
  script:
    - gofmt ./...

vet:
  image: golang
  stage: vetting
  script:
    - go vet ./...

unit_race_tests:
  image: golang
  stage: tests
  script:
    - go test -race ./...
