os: linux
dist: xenial
git:
  submodules: false
language: go
go: 1.13.x
go_import_path: perun.network/go-perun
env:
  - GO111MODULE=on
cache: 
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

jobs:
  include:
    - stage: lint_fmt_vet_misspell
      script:
        - go get -u golang.org/x/lint/golint github.com/client9/misspell/cmd/misspell
        - "! gofmt -l -s `ls -d */` | grep ."
        - "go vet ./..."
        - golint -set_exit_status ./...
        - misspell -error .

    - stage: unit_tests
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        - go test -timeout 60s -coverprofile c.out ./...
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

    - stage: unit_race_tests
      script:
        - go test -timeout 120s -race -gcflags=all=-d=checkptr=0 ./...
