os: linux
dist: xenial
git:
  submodules: false
language: go
go: 1.13.x
go_import_path: perun.network/go-perun
env:
  - GO111MODULE=on
cache: 
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
jobs:
  include:
    - stage: lint_fmt_vet_misspell
      script:
        - go get -u golang.org/x/lint/golint
        - golint -set_exit_status ./...
        - "! gofmt -l -s `ls -d */` | grep ."
        - "go vet ./..."
        - go get -u github.com/client9/misspell/cmd/misspell
        - misspell -error .

    - stage: unit_tests
      script:
        - go test -timeout 60s -cover ./...

    - stage: unit_race_tests
      script:
        - go test -timeout 120s -race ./...
